//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Guide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MachineId { get; set; }
        public string MountingOrientation { get; set; }
        public string VisionFilePath { get; set; }
        public string RobotSpeed { get; set; }
        public string RobotAccel { get; set; }
        public string MotionDelay { get; set; }
        public string XOffset { get; set; }
        public string YOffset { get; set; }
        public string CameraXScalling { get; set; }
        public string CameraYScalling { get; set; }
        public string RZOffset { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
