//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Guide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string RobotIP { get; set; }
        public string RobotPort { get; set; }
        public string VisionIP { get; set; }
        public string VisionPort { get; set; }
        public string LogfilePath { get; set; }
    }
}
